-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOajyIe3iM83WoSpE
OTnecaA0zudqFVcBDdStwZERDA6gCgYIKoZIzj0DAQehRANCAATgK8AKyjdYQdZl
1VFvO+r7JODKM/9NopMFl85Fqsg2DEs/fgfFbLFaV7r04FnEbY+aOmzfnlAT+Rx8
LpXcDDW6
-----END PRIVATE KEY-----