-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgsmv/eQl5fVqWLXA1
Al/r3Xu1FTlW4JNM0YY561swNrygCgYIKoZIzj0DAQehRANCAARR9Yx+brVUgHX3
xhMKjMtoY/uMaWjvZOLYlbUDk1PrxkMtPsaNINsSw/i2SAXQcAyiGW6Y2AzaBUW+
HdcHSLpE
-----END PRIVATE KEY-----