-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg7RIKDV/FEdQqI0ML
Gnxzz+HWyLLrFuP26q7mVOsA6nagCgYIKoZIzj0DAQehRANCAASJoPiHRKXwK1tV
D5q4TUVgTnJ9Zj/x+vYTU3KTirQ09qNa/nrf63KuhV1+IEnmqNIJZU/zTbMvLPcP
SGkrQpo1
-----END PRIVATE KEY-----