-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgb7hC7CndrEcI0UXv
DxiphEOcMDnA1A5KTuC/3EGUEbOgCgYIKoZIzj0DAQehRANCAAQnJaNtu28Z/WPo
AUAVq6F2idZzvEpeJvLrZmKTaTC0ifqXXf9nUP4ItrQ+boP6WWTjEODUB0CyAyv6
lsebnF3m
-----END PRIVATE KEY-----